#!/bin/bash

# LIB      holds the path to your libraries
# PROGRAM  holds the the path to the java binary
# CP       holds the classpath

LIB="./lib"
PROGRAM="./"

# Don't edit CP unless you're going to add to the class path
CP=".:$LIB/AmverseasBinFileUtils.jar:$LIB/commons-math3-3.6.1.jar:$PROGRAM"
#uncomment this line to compile the program. once compiled, comment this again.
#javac -cp $CP DecoderTestASCII.java
java -cp $CP BinConverter "$@"


